/**
 * axq-generate-tokens · generate.ts
 * @axqdesign/axq-generate-tokens v0.0.0
 *
 * Đọc @axqdesign/tokens/dist/tokens.json
 * → sinh ra TypeScript `export const` arrays + `export type` unions.
 *
 * Không dùng Sass compiler — đọc thẳng từ tokens.json đã build.
 * Mode --check: so sánh file hiện tại với output mới; exit 1 nếu stale (CI gate).
 *
 * Nguồn gốc: admin-icons/.build/generate-tokens.ts (Tabler Dashboard)
 * Viết lại sạch TypeScript bởi AXQ Design · https://axqdesign.axq
 *
 * Sử dụng:
 *   tsx src/generate.ts [--tokens=<path>] [--out=<path>] [--check]
 *
 * Mặc định:
 *   --tokens  axq-eco/packages/@axqdesign/tokens/dist/tokens.json
 *   --out     axq-eco/packages/@axqdesign/tokens/src/generated-types.ts
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

// ─── Types ────────────────────────────────────────────────────────────────────

/**
 * Expected shape of tokens.json.
 * All keys at every level become the union-type members — so the shape here must
 * exactly mirror what @axqdesign/tokens exports.
 */
interface TokensJson {
  primitive: {
    color: {
      brand:     Record<string, string>
      greyscale: Record<string, string>
      info:      Record<string, string>
      success:   Record<string, string>
      warning:   Record<string, string>
      error:     Record<string, string>
    }
    fontSize: Record<string, number>
    radius:   Record<string, number>
    spacing:  Record<string, number>
  }
  semantic: {
    color: {
      bg:      Record<string, string>
      surface: Record<string, string>
      text:    Record<string, string>
      icon:    Record<string, string>
      border:  Record<string, string>
      status:  Record<string, Record<string, string>>
      accent:  Record<string, string>
    }
    typography: Record<string, number>
    radius:     Record<string, number>
    spacing:    Record<string, number>
    inset:      Record<string, number>
    gap:        Record<string, number>
  }
  component: Record<string, Record<string, string | number>>
}

// ─── Args ─────────────────────────────────────────────────────────────────────

const __dirname  = dirname(fileURLToPath(import.meta.url))
const repoRoot   = join(__dirname, '../../..')
const argv       = process.argv.slice(2)
const checkMode  = argv.includes('--check')

const tokensPath = argv.find((a) => a.startsWith('--tokens='))?.split('=')[1]
  ?? join(repoRoot, 'axq-eco/packages/@axqdesign/tokens/dist/tokens.json')

const outFile = argv.find((a) => a.startsWith('--out='))?.split('=')[1]
  ?? join(repoRoot, 'axq-eco/packages/@axqdesign/tokens/src/generated-types.ts')

// ─── Code-gen helpers ─────────────────────────────────────────────────────────

/** Return sorted keys of an object as string[]. */
function keys(obj: Record<string, unknown>): string[] {
  return Object.keys(obj)
}

/** `export const fooNames = ['a', 'b'] as const` */
function constArray(varName: string, values: string[]): string {
  return `export const ${varName} = [${values.map((v) => `'${v}'`).join(', ')}] as const`
}

/** `export type FooName = 'a' | 'b'` */
function unionType(typeName: string, values: string[]): string {
  return `export type ${typeName} = ${values.map((v) => `'${v}'`).join(' | ')}`
}

/** Emit both a const array and a type alias for the same set of values. */
function emit(varName: string, typeName: string, values: string[]): string {
  return `${constArray(varName, values)}\n${unionType(typeName, values)}`
}

// ─── Read token source ────────────────────────────────────────────────────────

const tokens: TokensJson = JSON.parse(readFileSync(tokensPath, 'utf8'))

// Resolve package version from the sibling package.json (one dir up from dist/)
const tokensPkgPath = join(dirname(tokensPath), '../package.json')
const tokensVersion: string = existsSync(tokensPkgPath)
  ? (JSON.parse(readFileSync(tokensPkgPath, 'utf8')) as { version: string }).version
  : '0.0.0'

// ─── Build output ─────────────────────────────────────────────────────────────

const SEP = '// ' + '─'.repeat(77)

const blocks: string[] = [
  [
    '// Generated by axq-generate-tokens — DO NOT EDIT manually.',
    `// Regenerate: tsx tool/axq-generate-tokens/src/generate.ts`,
    `// Source: @axqdesign/tokens v${tokensVersion}`,
  ].join('\n'),

  // ── Primitive layer ──────────────────────────────────────────────────────────
  `${SEP}\n// Primitive\n${SEP}`,

  emit('brandColorNames', 'BrandColorName', keys(tokens.primitive.color.brand)),
  emit('greyscaleSteps',  'GreyscaleStep',  keys(tokens.primitive.color.greyscale)),

  // Status names are a fixed set — not read from tokens.json to keep them stable
  // even when tokens.json adds new keys to the info/success/… sub-objects.
  emit('statusNames', 'StatusName', ['info', 'success', 'warning', 'error']),

  emit('fontSizeValues', 'FontSizeValue', keys(tokens.primitive.fontSize)),
  emit('radiusNames',    'RadiusName',    keys(tokens.primitive.radius)),

  // ── Semantic layer ───────────────────────────────────────────────────────────
  `${SEP}\n// Semantic\n${SEP}`,

  emit('bgRoles',     'BgRole',     keys(tokens.semantic.color.bg)),
  emit('textRoles',   'TextRole',   keys(tokens.semantic.color.text)),
  emit('borderRoles', 'BorderRole', keys(tokens.semantic.color.border)),
  emit('iconRoles',   'IconRole',   keys(tokens.semantic.color.icon)),
  emit('accentNames', 'AccentName', keys(tokens.semantic.color.accent)),
  emit('typeRoles',   'TypeRole',   keys(tokens.semantic.typography)),

  emit('componentRadiusNames', 'ComponentRadiusName', keys(tokens.semantic.radius)),
  emit('spacingNames',         'SpacingName',         keys(tokens.semantic.spacing)),
  emit('insetNames',           'InsetName',           keys(tokens.semantic.inset)),
  emit('gapNames',             'GapName',             keys(tokens.semantic.gap)),

  // ── Component layer ──────────────────────────────────────────────────────────
  `${SEP}\n// Component\n${SEP}`,

  emit('componentNames', 'ComponentName', keys(tokens.component)),
]

const rawOutput = blocks.join('\n\n') + '\n'

// ─── Write or check ───────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log(`\n◆ axq-generate-tokens v0.0.0 · https://axqdesign.axq`)
  console.log(`  tokens: ${relative(repoRoot, tokensPath)}`)
  console.log(`  output: ${relative(repoRoot, outFile)}`)
  console.log(`  mode:   ${checkMode ? 'check' : 'generate'}\n`)

  // Format with the project's prettier config so the file passes lint checks.
  const prettierConfig = await resolveConfig(outFile)
  const formatted = await format(rawOutput, {
    ...prettierConfig,
    filepath: outFile,
    parser:   'typescript',
  })

  if (checkMode) {
    const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : ''
    if (current === formatted) {
      console.log(`✓ ${relative(repoRoot, outFile)} is up to date`)
      return
    }
    console.error(`✗ ${relative(repoRoot, outFile)} is stale`)
    console.error(`  Run: tsx tool/axq-generate-tokens/src/generate.ts`)
    process.exit(1)
  }

  writeFileSync(outFile, formatted)

  console.log(`✓ Generated ${relative(repoRoot, outFile)}`)
  console.log(`  Primitive:  brandColorNames, greyscaleSteps, statusNames, fontSizeValues, radiusNames`)
  console.log(`  Semantic:   bgRoles, textRoles, borderRoles, iconRoles, accentNames, typeRoles,`)
  console.log(`              componentRadiusNames, spacingNames, insetNames, gapNames`)
  console.log(`  Component:  componentNames\n`)
}

main().catch((err: unknown) => {
  console.error('✗', err)
  process.exit(1)
})
